Repository fack2/chatRoom, pull requests merged in 2019-11, with the labels that each got.

#5 write read-me
  README.md
Labels: in progress

#11 database#9
  server/database/dbBuild.js
  server/database/dbBuild.sql
  server/database/dbConnection.js
  server/database/initValue.sql
Labels: awaiting-review

#13 Signup
  client/components/SignUp/index.js
  client/components/index.js
  client/package-lock.json
  client/package.json
  client/redux/actions.js
  client/redux/reducer/index.js
  client/redux/reducer/signup.js
  client/redux/store/index.js
  package-lock.json
  package.json
  server/controllers/index.js
  server/controllers/signup.js
  server/controllers/validate.js
  server/controllers/validation.js
  server/database/queries/addUser.js
Labels: awaiting-review

#14 sender&reciever
  client/components/chatRoom/index.js
  client/components/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/addMessage.js
  server/controllers/getMessage.js
  server/controllers/getMessages.js
  server/controllers/index.js
  server/database/queries/addMessage.js
  server/database/queries/getMessage.js
  server/database/queries/getMessages.js
Labels: awaiting-review

#15 Redux
  client/components/chatRoom/index.js
  client/package-lock.json
  client/package.json
  client/redux/actions.js
  client/redux/reducer/chatRoomReducer.js
  client/redux/reducer/index.js
  client/redux/store/index.js
  server/index.js
Labels: awaiting-review

#18 Landing page #17
  client/components/Home/index.js
  client/components/index.js
Labels: awaiting-review

#21 Chat room style
  client/components/chatRoom/index.js
  client/redux/actions.js
  client/redux/reducer/chatRoomReducer.js
  server/controllers/index.js
Labels: awaiting-review

#22 profile Page
  client/components/index.js
  client/components/profile/index.js
  client/package-lock.json
  client/package.json
  client/redux/actions.js
  client/redux/reducer/index.js
  client/redux/reducer/userProfileReducer.js
  client/redux/store/index.js
  package-lock.json
  package.json
  server/controllers/index.js
  server/controllers/userInformation.js
  server/database/queries/getUserInformation.js
Labels: in progress, priority-2, technical
